import java.util.ArrayList;
import java.util.Iterator;

public class Fibonacci {

    public int sumOfEvens () {
//         System.out.println("\n#2: Each new term in the Fibonacci sequence is generated by adding" +
//                 " the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
//                 "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci " +
//                 "sequence whose values do not exceed four million, find the sum of the even-valued terms.\n");

        int x = 0;
        ArrayList<Long> y = new ArrayList<>();


        for (long i = 0, j = 1, k; j <= 4e6;) {
            k = j;
            j += i;
            i = k;
            if (j % 2 == 0) y.add(j);
//             System.out.println("i == " + i + " j == " + j);
//            System.out.println(y);
        }
        System.out.println(y);
        Iterator<Long> l = y.iterator();

        while(l.hasNext()) {
            x += l.next();
        }

        return x;
    }
}
